server:
  port: 8005

spring:
  application:
    name: cloud-hystrix-payment
  datasource:
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: password

mybatis:
  type-aliases-package: org.example.api.entities
  mapper-locations: classpath*:mapper/*.xml

ribbon:
  ReadTimeout: 5000
  connectTimeout: 5000

eureka:
  client:
    #表示自己是否注册EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/
  instance:
    instance-id: paymentHystrix8005
    prefer-ip-address: true

