server:
  port: 8000

spring:
  application:
    name: cloud-consumer
  zipkin:
    base-url: http://localhost:9941
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    #表示自己是否注册EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/
  instance:
    instance-id: consumer
    prefer-ip-address: true

# openFeign 默认的是 等待1秒就报错 我们要配置 超时时间即可
ribbon:
  ReadTimeout: 5000
  connectTimeout: 5000
logging:
  level:
    org.example.consumerFeign.service.PaymentFeignService: debug
feign:
  hystrix:
    enabled: true

